### ISSUE TITLE
Too many languages in kibble.json

### ISSUE THREAD

**Issue by gscragg** [shift72/core-template#79]
Based on a [conversation in another PR](https://github.com/indiereign/shift72-web/pull/149#issuecomment-744270226) adding all the languages into kibble.json is a monumentally bad idea.

This explains why the distributor sites take so long to render, because its creating 14 different versions for 500 odd films.

There is no need for a single language site (using shift72-tempalte) to also render 13 other language versions.

I feel the language files should exist in this repo, but the list of languages should not, and each downstream template should define its own set.

Perhaps this is fixed by not merging this config with the downstream one, and instead making the downstream one overwrite this one.

This is currently a performance burden on our servers.

**Comment by stajs** [comment]
@gscragg you fixed this for future sites in https://github.com/shift72/shift72-template/pull/9 while @PeculiarGoat has done the legwork to fix older sites in AB#3424.
